- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name:
        - nginx
        - snapd
      state: latest

  - name: "install snap core"
    snap:
      name: core

  - name: "remove old certbot"
    apt:
      name: certboy
      state: absent

  - name: "install certbot"
    snap:
      classic: yes
      name: certbot

  - name: "create www directory"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: "0775"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: "delete default nginx site"
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: "copy nginx nginx.conf"
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}
      owner: root
      group: root
      mode: "0644"
    notify: restart nginx

  - name: "install certificate"
    become: true
    shell: /snap/bin/certbot certonly --nginx -n -d {{ domain }} --agree-tos -m {{ email }}
    notify: restart nginx
    register: certbot
    changed_when: "'no action taken' not in certbot.stdout"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
