- hosts: web
  tasks:
    - name: "publish"
      synchronize:
        src: "../build/"
        dest: "/var/www/{{ domain }}"
        archive: no
        checksum: yes
        recursive: yes
        delete: yes
      become: no
